# -*- mode: yaml; coding: utf-8; indent-tabs-mode: nil; tab-width: 2 -*-
language: emacs-lisp

env:
  matrix:
    - EMACS=emacs-26.2-travis
    - EMACS=emacs-26.3-travis
    - EMACS=emacs-git-snapshot-travis

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy install-info
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - git clone https://github.com/rejeep/evm.git /usr/local/evm
  - export PATH=/usr/local/evm/bin:${PATH}
  - evm config path /tmp

install:
  - evm install ${EMACS}
  - evm use ${EMACS}

before_script:
  - emacs --version
  - rake travis

script:
  - rake tests
