# -*- mode: yaml; coding: utf-8; indent-tabs-mode: nil; tab-width: 2 -*-
language: emacs-lisp

env:
  matrix:
    - EMACS=emacs-24.5-travis METHOD=evm
    - EMACS=emacs-snapshot METHOD=ppa

branches:
  only:
    - master

before_install:
  - if [ "$METHOD" = 'evm' ]; then
        export PATH="/home/travis/.evm/bin:$PATH" &&
        git clone https://github.com/rejeep/evm.git /home/travis/.evm &&
        evm config path /tmp;
    fi
  - if [ "$METHOD" = 'ppa' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa;
    fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy install-info

install:
  - if [ "$METHOD" = 'evm' ]; then
        evm install ${EMACS} --use --skip;
    fi
  - if [ "$METHOD" = 'ppa' ]; then
        sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el;
    fi

before_script:
  - emacs --version
  - rake travis

script:
  - rake test
