# -*- mode: yaml; coding: utf-8; indent-tabs-mode: nil; tab-width: 2 -*-
language: emacs-lisp

env:
  matrix:
    - EMACS=emacs-24.4-bin METHOD=evm
    - EMACS=emacs-snapshot METHOD=ppa

branches:
  only:
    - master

before_install:
  - if [ "$METHOD" = 'evm' ]; then
        sudo mkdir /usr/local/evm &&
        sudo chown travis:travis /usr/local/evm &&
        curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash &&
        export PATH="$HOME/.evm/bin:$PATH";
    fi
  - if [ "$METHOD" = 'ppa' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa;
    fi
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy install-info

install:
  - if [ "$METHOD" = 'evm' ]; then
        evm install ${EMACS} --use;
    fi
  - if [ "$METHOD" = 'ppa' ]; then
        sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el;
    fi

before_script:
  - emacs --version
  - rake travis

script:
  - rake test
