# -*- mode: yaml; coding: utf-8; indent-tabs-mode: nil; tab-width: 2 -*-
language: emacs-lisp

env:
  matrix:
    - EMACS=emacs-24.5-travis
    - EMACS=emacs-25.3-travis
    - EMACS=emacs-git-snapshot-travis

branches:
  only:
    - master

before_install:
  - export PATH="/home/travis/.evm/bin:$PATH"
  - git clone https://github.com/rejeep/evm.git /home/travis/.evm
  - evm config path /tmp
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy install-info

install:
  - evm install ${EMACS} --use --skip

before_script:
  - emacs --version
  - rake travis

script:
  - rake test
